#!/bin/sh

# make sure to do a git commit before running so you don't get bogus commit messages

set -e
set -x

( cd taglibs ;
  rm -f hobo-contrib-all.dryml;
  for f in *.dryml ; do
      echo  "<include src=\"${f%%.dryml}\" plugin=\"hobo-contrib\" />" >> hobo-contrib-all.dryml;
  done ;
 )
git add taglibs/hobo-contrib-all.dryml
git commit -m "update autogenerated files" || true
git push origin master
( cd ../hobo-contrib-makedoc ;
  rake ../hobo-contrib-gh-pages/documentation.html )
( cd ../hobo-contrib-gh-pages ;
  git commit -a -m "doc update" || true; 
  git push origin gh-pages)