# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{hobosupport}
  s.version = "1.0.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Tom Locke"]
  s.date = %q{2011-02-25}
  s.email = %q{tom@tomlocke.com}
  s.files = [
    "CHANGES.txt",
    "README.txt",
    "Rakefile",
    "hobosupport.gemspec",
    "lib/hobo_support.rb",
    "lib/hobo_support/array.rb",
    "lib/hobo_support/blankslate.rb",
    "lib/hobo_support/enumerable.rb",
    "lib/hobo_support/fixes.rb",
    "lib/hobo_support/fixes/chronic.rb",
    "lib/hobo_support/fixes/module.rb",
    "lib/hobo_support/fixes/pp.rb",
    "lib/hobo_support/hash.rb",
    "lib/hobo_support/implies.rb",
    "lib/hobo_support/metaid.rb",
    "lib/hobo_support/methodcall.rb",
    "lib/hobo_support/methodphitamine.rb",
    "lib/hobo_support/module.rb",
    "lib/hobo_support/string.rb",
    "lib/hobosupport.rb",
    "test/hobosupport.rdoctest",
    "test/hobosupport/enumerable.rdoctest",
    "test/hobosupport/hash.rdoctest",
    "test/hobosupport/implies.rdoctest",
    "test/hobosupport/metaid.rdoctest",
    "test/hobosupport/methodphitamine.rdoctest",
    "test/hobosupport/module.rdoctest"
  ]
  s.homepage = %q{http://hobocentral.net/}
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{hobosupport}
  s.rubygems_version = %q{1.4.2}
  s.summary = %q{Core Ruby extensions from the Hobo project}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

