source "http://rubygems.org"

# for rails 2.2.2 we'll lock down some older versions just to widen our test
gem "rails", "= 2.2.2"
gem "will_paginate", "= 2.3.12"
gem "bluecloth", "= 2.0.1"
gem "RedCloth", "= 4.1.1", :require => "redcloth"
gem "mysql", "= 2.8.1"
gem "yard"
gem "jeweler"
gem "rubydoctest", :git => "git://github.com/tablatom/rubydoctest.git", :branch => "master"
gem "activerecord-comments", :git => "git://github.com/bryanlarsen/activerecord-comments.git", :branch => "master"
gem "rubigen", "= 1.3.4"  # compatible with old activesupport
