source "http://rubygems.org"

gem 'rubydoctest', :git => 'git://github.com/bryanlarsen/rubydoctest.git'
gem 'rails', '3.2.8'
gemspec :path => "../dryml"
gemspec :path => "../hobo_support"
gemspec :path => "../hobo_fields"
gemspec
gem 'will_paginate', :git => 'git://github.com/bryanlarsen/will_paginate.git'
