require 'rake'
require 'rake/rdoctask'
require 'rake/testtask'

require 'active_record'
ActiveRecord::ActiveRecordError # hack for https://rails.lighthouseapp.com/projects/8994/tickets/2577-when-using-activerecordassociations-outside-of-rails-a-nameerror-is-thrown
$:.unshift File.expand_path('../lib', __FILE__)
$:.unshift File.expand_path('../../hobo_support/lib', __FILE__)
$:.unshift File.expand_path('../../hobo_fields/lib', __FILE__)
$:.unshift File.expand_path('../../dryml/lib', __FILE__)
require 'hobo'

RUBY = File.join(Config::CONFIG['bindir'], Config::CONFIG['ruby_install_name']).sub(/.*\s.*/m, '"\&"')
RUBYDOCTEST = ENV['RUBYDOCTEST'] || "#{RUBY} -S rubydoctest"

desc "Default Task"
task :default => [ :test ]


# --- Testing --- #

desc "Run all unit tests"
Rake::TestTask.new(:test) { |t|
  t.libs << "test"
  t.test_files=Dir.glob( "test/**/*_test.rb" ).sort
  t.verbose = true
}

namespace "test" do
  desc "Run the doctests"
  task :doctest do |t|
    files=Dir['doctest/*.rdoctest'].map {|f| File.expand_path(f)}.join(' ')
    # note, tests in doctest/hobo/ are out of date
    exit(1) if !system("#{RUBYDOCTEST} #{files}")
  end

  desc "Run the irt tests"
  task :irt => :prepare_testapp do |t|
    chdir '/tmp/hobo_testapp'
    sh %(irt #{File.expand_path('../', __FILE__)})
  end

  desc "Prepare a rails application for testing"
  task :prepare_testapp, :force do |t, args|
    args.with_default(:force => false)
    path = "/tmp/hobo_testapp"
    if args.force || !File.directory?(path)
      remove_entry_secure( path, true )
      sh %(hobo new #{path} --skip-wizard)
      chdir path
      sh %(echo "gem 'irt', :group => :console" >> Gemfile) # to make the bundler happy
      sh %(echo "" > app/models/.gitignore) # because git reset --hard would rm the dir
      rm %(.gitignore) # we need to reset everything in a testapp
      sh %(git init && git add . && git commit -m "initial commit")
      puts %(The testapp has been created in '#{path}')
    else
      chdir path
      sh %(git add .)
      sh %(git reset --hard -q HEAD)
    end
  end
end

# --- RDoc --- #

desc 'Generate documentation for the Hobo plugin.'
Rake::RDocTask.new(:rdoc) do |rdoc|
  rdoc.rdoc_dir = 'rdoc'
  rdoc.title    = 'Hobo'
  rdoc.options << '--line-numbers' << '--inline-source'
  rdoc.rdoc_files.include('README')
  rdoc.rdoc_files.include('lib/**/*.rb')
end


