require 'rake'
require 'rake/rdoctask'
require 'rake/testtask'

require 'active_record'
ActiveRecord::ActiveRecordError # hack for https://rails.lighthouseapp.com/projects/8994/tickets/2577-when-using-activerecordassociations-outside-of-rails-a-nameerror-is-thrown
$:.unshift File.expand_path('../lib', __FILE__)
$:.unshift File.expand_path('../../hobo_support/lib', __FILE__)
$:.unshift File.expand_path('../../hobo_fields/lib', __FILE__)
$:.unshift File.expand_path('../../dryml/lib', __FILE__)
require 'hobo'

RUBY = File.join(Config::CONFIG['bindir'], Config::CONFIG['ruby_install_name']).sub(/.*\s.*/m, '"\&"')
RUBYDOCTEST = ENV['RUBYDOCTEST'] || "#{RUBY} -S rubydoctest"

desc "Default Task"
task :default => [ :test ]


# --- Testing --- #

desc "Run all unit tests"
Rake::TestTask.new(:test) { |t|
  t.libs << "test"
  t.test_files=Dir.glob( "test/**/*_test.rb" ).sort
  t.verbose = true
}

namespace "test" do
  desc "Run the doctests"
  task :doctest do |t|
    files=Dir['doctest/*.rdoctest'].map {|f| File.expand_path(f)}.join(' ')
    # note, tests in doctest/hobo/ are out of date
    exit(1) if !system("#{RUBYDOCTEST} #{files}")
  end
end

# --- RDoc --- #

desc 'Generate documentation for the Hobo plugin.'
Rake::RDocTask.new(:rdoc) do |rdoc|
  rdoc.rdoc_dir = 'rdoc'
  rdoc.title    = 'Hobo'
  rdoc.options << '--line-numbers' << '--inline-source'
  rdoc.rdoc_files.include('README')
  rdoc.rdoc_files.include('lib/**/*.rb')
end


TESTAPP_PATH = '/tmp/testapp'
ROOT_PATH = File.expand_path('../', __FILE__)

require 'fileutils'
desc "Prepare a rails-hobo application for testing"
task :prepare_testapp do |t|
  remove_entry_secure( TESTAPP_PATH, true )
  sh %(hobo new #{TESTAPP_PATH} --skip-wizard)
  chdir TESTAPP_PATH
  sh %(echo "gem 'irt', '>= 0.7.5', :group => :console" >> Gemfile)
  sh %(echo "" > app/models/.gitignore) # because git reset --hard would rm the dir
  sh %(git init && git add . && git commit -m "initial commit")
  puts %(The appdir has been created in '#{TESTAPP_PATH}')
end


desc "Run all irt tests"
task :irt_test_all => [:prepare_testapp] do |t|
  sh %(irt #{ROOT_PATH})
end

