source 'http://rubygems.org'

gem 'rails', '3.2.8'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'sqlite3'

# Use unicorn as the web server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger (ruby-debug for Ruby 1.8.7+, ruby-debug19 for Ruby 1.9.2+)
# gem 'ruby-debug'
group :development do
  gem 'debugger'
end

# Bundle the extra gems:
# gem 'bj'
# gem 'nokogiri'
# gem 'sqlite3-ruby', :require => 'sqlite3'
# gem 'aws-s3', :require => 'aws/s3'

# Bundle gems for the local environment. Make sure to
# put test-only gems in this group so their generators
# and rake tasks are available in development mode:
# group :development, :test do
#   gem 'webrat'
# end
#gem "hobo_support", :path => "../.."
#gem "hobo_fields", :path => "../.."
#gem "dryml", :path => "../.."
gem "hobo", :path => "../.."
# gem "hobo_rapid", :path => "../.."
# gem "hobo_clean", :path => "../.."
# gem "hobo_clean_sidemenu", :path => "../.."
# gem "hobo_jquery", :path => "../.."
# gem "hobo_jquery_ui", :path => "../.."

gem "jquery-ui-themes", "~> 0.0.4"

#gem "hobo_bootstrap", :git => "git://github.com/Hobo/hobo_bootstrap"
gem "hobo_bootstrap", :path => "../../../hobo_bootstrap"

gem "will_paginate", :git => "git://github.com/Hobo/will_paginate.git"

gem "bluecloth"
gem "RedCloth"

gem "shoulda", :group => :test
gem "factory_girl_rails", :group => :test

group :development, :test do
  gem 'capybara', :git => 'git://github.com/jnicklas/capybara.git'#, :ref => "83d8574c1d"  #"756ec1b2af70c66093c3b25976f520a3e6c3c2ae"
#  gem 'capybara-webkit', :git => 'git://github.com/thoughtbot/capybara-webkit.git'
  gem 'capybara-webkit', :git => 'https://github.com/josephbridgwaterrowe/capybara-webkit.git', :branch => 'patch-1'
  gem 'database_cleaner'
end

gem "jquery-rails"

#gem "hobo-jquery", :git => "git://github.com/bryanlarsen/hobo-jquery.git", :branch => "no-prototype"

gem 'paperclip', :git => "git://github.com/thoughtbot/paperclip.git", :branch => "master"

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  gem 'therubyracer', :platforms => :ruby

  gem 'uglifier', '>= 1.0.3'
end

gem 'awesome_print'

gem "hobo_simple_color", :git => "git://github.com/Hobo/hobo_simple_color"
gem "hobo_tokeninput", :git => "git://github.com/Hobo/hobo_tokeninput"

# gem 'dryml-firemarker', :require => 'dryml13-firemarker', :group => :development, :path => '/work/dryml-firemarker'

# gem "quiet_assets"
