source "http://rubygems.org"

# for rails 2.2.2 we'll lock down some older versions just to widen our test
gem "rails", "= 2.3.11"
gem "will_paginate", "~> 2.3"
gem "BlueCloth", "~> 1.0", :require => "bluecloth"
gem "RedCloth", "~> 4.2", :require => "redcloth"
gem "activerecord-jdbcmysql-adapter", "~> 1.1"
gem "yard"
gem "jeweler"
gem "rubydoctest", :git => "git://github.com/tablatom/rubydoctest.git", :branch => "master"
gem "activerecord-comments", :git => "git://github.com/bryanlarsen/activerecord-comments.git", :branch => "master"
gem "rubigen"
