source "http://rubygems.org"

gem 'rubydoctest', :git => 'git://github.com/bryanlarsen/rubydoctest.git'
gem 'rails'
gem 'yard'
gem 'protected_attributes'

gemspec :path => "../hobo_support"
gemspec
platform :ruby do
  gem 'sqlite3'
end
platform :jruby do
  gem 'activerecord-jdbcsqlite3-adapter'
end
