# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{dryml}
  s.version = "1.1.0.pre4"

  s.required_rubygems_version = Gem::Requirement.new("> 1.3.1") if s.respond_to? :required_rubygems_version=
  s.authors = ["Tom Locke"]
  s.date = %q{2011-02-24}
  s.email = %q{tom@tomlocke.com}
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    "CHANGES.txt",
    "LICENSE.txt",
    "README",
    "Rakefile",
    "TODO.txt",
    "dryml.gemspec",
    "lib/dryml.rb",
    "lib/dryml/dryml_builder.rb",
    "lib/dryml/dryml_doc.rb",
    "lib/dryml/dryml_generator.rb",
    "lib/dryml/dryml_support_controller.rb",
    "lib/dryml/helper.rb",
    "lib/dryml/parser.rb",
    "lib/dryml/parser/attribute.rb",
    "lib/dryml/parser/base_parser.rb",
    "lib/dryml/parser/document.rb",
    "lib/dryml/parser/element.rb",
    "lib/dryml/parser/elements.rb",
    "lib/dryml/parser/source.rb",
    "lib/dryml/parser/text.rb",
    "lib/dryml/parser/tree_parser.rb",
    "lib/dryml/part_context.rb",
    "lib/dryml/scoped_variables.rb",
    "lib/dryml/static_tags",
    "lib/dryml/tag_parameters.rb",
    "lib/dryml/taglib.rb",
    "lib/dryml/template.rb",
    "lib/dryml/template_environment.rb",
    "lib/dryml/template_handler.rb",
    "taglibs/core.dryml",
    "test/dryml.rdoctest"
  ]
  s.homepage = %q{http://hobocentral.net/}
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{hobo}
  s.rubygems_version = %q{1.4.2}
  s.summary = %q{The web app builder for Rails}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<hobosupport>, ["= 1.1.0.pre4"])
      s.add_runtime_dependency(%q<actionpack>, [">= 2.2.2", "< 3.0.0"])
    else
      s.add_dependency(%q<hobosupport>, ["= 1.1.0.pre4"])
      s.add_dependency(%q<actionpack>, [">= 2.2.2", "< 3.0.0"])
    end
  else
    s.add_dependency(%q<hobosupport>, ["= 1.1.0.pre4"])
    s.add_dependency(%q<actionpack>, [">= 2.2.2", "< 3.0.0"])
  end
end

