require 'rake'
require 'rake/rdoctask'
require 'rake/testtask'

$:.unshift File.join(File.expand_path(File.dirname(__FILE__)), '/lib')
$:.unshift File.join(File.expand_path(File.dirname(__FILE__)), '/../hobosupport/lib')
require 'dryml' # to get VERSION

RUBY = File.join(Config::CONFIG['bindir'], Config::CONFIG['ruby_install_name']).sub(/.*\s.*/m, '"\&"')
if defined?(Bundler)
  RUBYDOCTEST = 'bundle exec rubydoctest'
else
  RUBYDOCTEST = ENV['RUBYDOCTEST'] || "#{RUBY} -S rubydoctest"
end

desc "Default Task"
task :default => [ :test ]

# --- Testing --- #

desc "Run all tests"
task :test do |t|
  files=Dir['test/*.rdoctest'].map {|f| File.expand_path(f)}.join(' ')
  exit(1) if !system("#{RUBYDOCTEST} #{files}")
end

# --- RDOC --- #

require 'yard'
YARD::Rake::YardocTask.new do |t|
  t.files = ['lib/**/*.rb', 'README', 'LICENSE.txt', 'CHANGES.txt']
end

# --- Packaging and Rubyforge & gemcutter & github--- #

require 'jeweler'
Jeweler::Tasks.new do |gemspec|
  gemspec.version      = Dryml::VERSION
  gemspec.name         = "dryml"
  gemspec.email        = "tom@tomlocke.com"
  gemspec.summary      = "The web app builder for Rails"
  gemspec.homepage     = "http://hobocentral.net/"
  gemspec.authors      = ["Tom Locke"]
  gemspec.rubyforge_project = "hobo"
  gemspec.add_dependency("hobosupport", ["= #{Dryml::VERSION}"])
  gemspec.add_dependency("actionpack", [">= 2.2.2", "< 3.0.0"])
end
Jeweler::GemcutterTasks.new
