require 'rake'
require 'rdoc/task'
require 'rake/testtask'

RUBY = File.join(RbConfig::CONFIG['bindir'], RbConfig::CONFIG['ruby_install_name']).sub(/.*\s.*/m, '"\&"')
RUBYDOCTEST = ENV['RUBYDOCTEST'] || "#{RUBY} -S rubydoctest"

# --- Testing --- #

namespace "test" do
  desc "Run the doctests"
  task :doctest do |t|
    files=Dir['test/**/*.rdoctest'].map {|f| File.expand_path(f)}.join(' ')
    exit(1) if !system("#{RUBYDOCTEST} #{files}")
  end
end

# --- RDOC --- #

require 'rubygems'
require 'yard'
YARD::Rake::YardocTask.new do |t|
  t.files = ['lib/**/*.rb', 'README', 'LICENSE.txt', 'CHANGES.txt']
end
